### PR TITLE
Suppress error messages for invalid file names

### PR DESCRIPTION
**Pull request by annda**
This is not the media manager, where problems should be fixed.

### CODE REVIEW

**Comment by Michaelsy** [comment]
I am not sure if I really understood this PR correctly. But as far as I can see, I think that's no improvement, because media files can also be uploaded directly to the server (and there are many reasons to do so). This will not call the media manager.

But maybe there is another reason for this PR, which is not mentioned here.

**Comment by Michaelsy** [comment]
In the meantime I have looked at the concrete behavior before and after applying the patch. A pity, a real loss of function.

**Comment by splitbrain** [comment]
Huh? There is no functionality lost. But messages a user might not be able to act on are no longer shown. The behavior in the media manager (where users can actually act) continue to show the message.

**Comment by Michaelsy** [comment]
The loss of functionality is that the user is not informed that something have gone wrong. He does not know that something that exists is not listed.

If he is the admin himself, then he can correct that. If he is not the admin, then he can inform his admin.

I especially look at the case where the admin uploads files directly to the server. I think that is not a rare case.

If you only work with the media manager, it does not matter anyway, then this mistake can not happen anyway. (As far as I've noticed, wrong file names are corrected automatically in Media Manager.)

**Comment by Michaelsy** [comment]
Here is a live demo: http://dw-livedemos.informantum.de/doku.php?id=livedemos:test-filelisting:start

**Pull request merged**
